// tests/esp_stubs/esp_tls_errors.h —— host 语法门桩(对齐 IDF 5.5.3 esp-tls)。
// 仅覆盖 meta_store_api.c OPEN 死因分类用到的符号。
#pragma once

#define ESP_ERR_ESP_TLS_BASE 0x8000

#define ESP_ERR_ESP_TLS_CANNOT_RESOLVE_HOSTNAME (ESP_ERR_ESP_TLS_BASE + 0x01)
#define ESP_ERR_ESP_TLS_CANNOT_CREATE_SOCKET    (ESP_ERR_ESP_TLS_BASE + 0x02)
#define ESP_ERR_ESP_TLS_UNSUPPORTED_PROTOCOL_FAMILY (ESP_ERR_ESP_TLS_BASE + 0x03)
#define ESP_ERR_ESP_TLS_FAILED_CONNECT_TO_HOST  (ESP_ERR_ESP_TLS_BASE + 0x04)
#define ESP_ERR_ESP_TLS_SOCKET_SETOPT_FAILED    (ESP_ERR_ESP_TLS_BASE + 0x05)
#define ESP_ERR_ESP_TLS_CONNECTION_TIMEOUT      (ESP_ERR_ESP_TLS_BASE + 0x06)
#define ESP_ERR_ESP_TLS_SERVER_HANDSHAKE_TIMEOUT (ESP_ERR_ESP_TLS_BASE + 0x09)

// esp_tls.h 桩里 esp_tls_error_type_t 的枚举值(与 IDF 顺序一致)。
typedef enum {
    ESP_TLS_ERR_TYPE_UNKNOWN = 0,
    ESP_TLS_ERR_TYPE_SYSTEM,
    ESP_TLS_ERR_TYPE_MBEDTLS,
    ESP_TLS_ERR_TYPE_MBEDTLS_CERT_FLAGS,
    ESP_TLS_ERR_TYPE_ESP,
    ESP_TLS_ERR_TYPE_WOLFSSL,
    ESP_TLS_ERR_TYPE_WOLFSSL_CERT_FLAGS,
    ESP_TLS_ERR_TYPE_MAX,
} esp_tls_error_type_t;
